# Python para Análise de Dados - Wes McKinney Cap. IV

# Introdução ao NumPy - Prof. Dr. Anselmo R. Pitombeira Neto.

In [2]:
# Criação de vector (tensor) uni-dimensional.
import numpy as np

v = np.array([1, 2, 3, 4])
print(f"v = {v}")

v = [1 2 3 4]


In [12]:
# Tipo de elementos.
v.dtype

dtype('int32')

In [11]:
np.array([1.5, 2.2, 3.0]).dtype

dtype('float64')

In [14]:
# Forma do tensor.
v = np.array([1, 2, 3, 4])
v.shape

(4,)

In [23]:
# Criando um tensor bi-dimensional v.shape = (linha, coluna).
v.shape = (2, 2)
v

array([[1, 2],
       [3, 4]])

In [25]:
# Ou.
v = np.array([1, 2, 3, 4]).reshape(2, 2)
v

array([[1, 2],
       [3, 4]])

In [30]:
v.reshape(4, 1)

array([[1],
       [2],
       [3],
       [4]])

In [34]:
# A função reshape aceita o uso de -1 como dimensão na especificação do shape.
# A função reshape determina automaticamente o nr de elementos em cada dimensão de forma a manter o nr total de elementos.
# v.reshape(linha, -1)
v = np.array([1, 2, 3, 4, 5, 6, 7, 8])
v = v.reshape(2, -1)
v

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8])
v = v.reshape(-1, 4)
v

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
# Número de eixos (ou dimensões) e número total de elementos.
print(f"Número de dimensões: {v.ndim}")
print(f"Número de elementos: {v.size}")

Número de dimensões: 2
Número de elementos: 8


In [57]:
v = np.array(range(50)).reshape(10, 5)
print(f"v =\n{v}")
print()
print(f"Número de dimensões: {v.ndim}")
print(f"Número de elementos: {v.size}")

v =
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]

Número de dimensões: 2
Número de elementos: 50


In [62]:
# Criando tensores.
V = np.zeros((3,3))
print('V = \n', V)

U = np.ones((3,3))
print('U = \n', U)

D = np.diag([10, 10, 10])
print('D = \n', D)

V = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
U = 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
D = 
 [[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [71]:
# Criação de sequências como tensores.
v = np.arange(0, 5, 0.5)              # 0 a 5 com passo de 0.5.
u = np.linspace(0, 5, 11)             # 0 a 5 separados em 10 partes iguais.
print("v =", v)
print("u =", u)

v = [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
u = [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [78]:
# Devolvendo um tensor para uma dimensão.
v = np.array(range(50)).reshape(10, 5)
print(f"v =\n{v}")
print()
print(f"v.flatten = \n{v.flatten()}")

v =
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]

v.flatten = 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [81]:
# Acessando partes ou elementos de tensores.
print(v[0, 1])
print(v[2, 0])
print(v[1])

1
10
[5 6 7 8 9]


In [82]:
# Gerando tensor a partir de outro tensor.
v = np.arange(10)
print(v)
print()
u = v[1:3]
print(u)

[0 1 2 3 4 5 6 7 8 9]

[1 2]


In [84]:
A = np.arange(15).reshape(3,5)
print(A)
print()
subA = A[0:2, 2:4]
print(subA)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[2 3]
 [7 8]]


In [3]:
# Tomar um valor de xarr sempre que o valor correspondente em cond seja True e, caso contrário, tomar o valor de yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [9]:
# Substituir todos os valores positivos por 1 e todos os valores negativos por –1.
arr = np.random.randn(4, 4)
print(arr)
print()
print(arr > 0)
print()
print(np.where(arr > 0, 1, -1))

[[-3.36300582 -1.95073452 -0.55430289  0.38587163]
 [-2.19661112 -1.19682317 -1.20665735  1.25093112]
 [-0.46634108  0.90796436  1.23914556 -0.5975908 ]
 [ 0.14344653 -0.18856767 -1.23933257 -1.23515191]]

[[False False False  True]
 [False False False  True]
 [False  True  True False]
 [ True False False False]]

[[-1 -1 -1  1]
 [-1 -1 -1  1]
 [-1  1  1 -1]
 [ 1 -1 -1 -1]]


In [10]:
# Substituir todos os valores positivos em arr pela constante 1.
print(np.where(arr > 0, 1, arr))

[[-3.36300582 -1.95073452 -0.55430289  1.        ]
 [-2.19661112 -1.19682317 -1.20665735  1.        ]
 [-0.46634108  1.          1.         -0.5975908 ]
 [ 1.         -0.18856767 -1.23933257 -1.23515191]]


## Operação com Tensores
- As operações sobre tensores NumPy são realizada elemento a elemento.

In [86]:
# Soma.
v = np.array([10, 20, 30])
u = np.array([3, 2, 1])
w = u + v
print(w)

[13 22 31]


In [88]:
# Multiplicação e divisão.
w = u*v
print("w =", w)
x = v/u
print("x =", x)

w = [30 40 30]
x = [ 3.33333333 10.         30.        ]


In [91]:
# Potenciação.
x = np.array([3, 5])
y = x**2
print(y)

[ 9 25]


In [110]:
# Média, mínimo, máximo. 
x = np.arange(1, 21).reshape(4, -1)
print(f"x =\n{x}")
print()
media = x.mean()
menor_valor = np.min(x)
maior_valor = np.max(x)
print(f"Média = {media}")
print(f"Menor valor = {menor_valor}")
print(f"Maior valor = {maior_valor}")

x =
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Média = 10.5
Menor valor = 1
Maior valor = 20


In [112]:
# Produto escalar.
v = np.array([10, 20, 30])
u = np.array([3, 2, 1])
w = np.dot(u, v)
print("w =", w)

w = 100
x = 100


In [113]:
# Multiplicação de um escalar por um vetor:
x = 10*w
print("x =", x)

x = 1000


## Matrizes

In [115]:
# Criando uma matriz.
A = np.array([[10, 20, 30], [30, 40, 50], [50, 60, 70]])
print(f"A =\n{A}")

A =
[[10 20 30]
 [30 40 50]
 [50 60 70]]


In [116]:
# Matriz identidade.
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [119]:
# Matriz diagonal.
D = np.diag(np.arange(1.0, 4.0))
print(D)

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]


In [129]:
# Produto vectorial.
v = np.array([10, 10])
A = np.arange(1, 5).reshape(2, 2)
u = A.dot(v)
print(f"v x A =\n {A} x {v}")
print()
print(f"u =\n{u}")

v x A =
 [[1 2]
 [3 4]] x [10 10]

u =
[30 70]


In [134]:
A = np.ones((3, 3))
B = 10*np.ones((3, 3))
C = np.dot(A, B)
print(C)

[[30. 30. 30.]
 [30. 30. 30.]
 [30. 30. 30.]]


In [144]:
# Transposição de matrizes.
A = np.arange(4).reshape(2,2)
print(f"A =\n{A}")
print()
print("Transposta de A =\n", A.transpose())
print()
print("  Ou")
print()
print("Transposta de A =\n", A.T)

A =
[[0 1]
 [2 3]]

Transposta de A =
 [[0 2]
 [1 3]]

  Ou

Transposta de A =
 [[0 2]
 [1 3]]


## Álgebra Linear
- O NumPy possui um submódulo especí¦co para a realização de operações típicas da álgebra linear chamado linalg.
- Com este módulo é possível resolver sistemas lineares, obter inversas de matrizes, calcular autovalores e autovetores, etc.

In [147]:
# Solução de sistemas lineares.
A = np.array([10, 20, 30, 40]).reshape(2,2)
B = np.array([5, 10])
x = np.linalg.solve(A, B)
print(f"Solução: {x}")

Solução: [0.   0.25]


In [155]:
# Matriz inversa.
A = np.array([10, 20, 30, 40]).reshape(2,2)
print(f"A =\n {A}")
print()
inv_A = np.linalg.inv(A)
print(f"Matriz inversa =\n{inv_A}")

A =
 [[10 20]
 [30 40]]

Matriz inversa =
[[-0.2   0.1 ]
 [ 0.15 -0.05]]


In [156]:
# Rank e determinante.
rank_A = np.linalg.matrix_rank(A)
print("Rank de A =",rank_A)
det_A = np.linalg.det(A)
print("Determinante de A = %.2f" % det_A)

Rank de A = 2
Determinante de A = -200.00
